Repository opensrp/opensrp-server-web, pull requests merged in 2020-10, with the labels that each got.

#489 Search clients with relationships
  pom.xml
  src/main/java/org/opensrp/web/rest/ClientResource.java
  src/test/java/org/opensrp/web/rest/ClientResourceTest.java
Labels: v2.1

#457 Replicate: update the json validator identifier parameter passing
  src/main/java/org/opensrp/web/bean/JsonWidgetValidatorDefinition.java
  src/main/java/org/opensrp/web/rest/ClientFormResource.java
  src/main/java/org/opensrp/web/utils/ClientFormValidator.java
  src/test/java/org/opensrp/web/rest/ClientFormResourceTest.java
  src/test/java/org/opensrp/web/utils/ClientFormValidatorTest.java
Labels: Form configuration

#576 replicate the location tag fetch endpoint
  pom.xml
  src/main/java/org/opensrp/web/rest/LocationTagResource.java
  src/test/java/org/opensrp/web/rest/LocationTagResourceTest.java
Labels: enhancement
